www.praiser.pp.ua [Sun Feb 06 20:31:40 2022] [error] [pid 85014] src/server/mod_wsgi.c(3692): [client 188.163.113.8:47234] mod_wsgi (pid=85014): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:31:40 2022] [error] [pid 85014] src/server/wsgi_logger.c(630): [client 188.163.113.8:47234] mod_wsgi (pid=85014): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:31:40 2022] [error] [pid 85014] src/server/wsgi_logger.c(147): [client 188.163.113.8:47234] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:31:40 2022] [error] [pid 85014] src/server/wsgi_logger.c(147): [client 188.163.113.8:47234]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 1, in <module>
www.praiser.pp.ua [Sun Feb 06 20:31:40 2022] [error] [pid 85014] src/server/wsgi_logger.c(147): [client 188.163.113.8:47234]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:31:40 2022] [error] [pid 85014] src/server/wsgi_logger.c(147): [client 188.163.113.8:47234] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:31:40 2022] [error] [pid 85576] src/server/mod_wsgi.c(3692): [client 188.163.113.8:47306] mod_wsgi (pid=85576): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:31:40 2022] [error] [pid 85576] src/server/wsgi_logger.c(630): [client 188.163.113.8:47306] mod_wsgi (pid=85576): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:31:40 2022] [error] [pid 85576] src/server/wsgi_logger.c(147): [client 188.163.113.8:47306] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:31:40 2022] [error] [pid 85576] src/server/wsgi_logger.c(147): [client 188.163.113.8:47306]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 1, in <module>
www.praiser.pp.ua [Sun Feb 06 20:31:40 2022] [error] [pid 85576] src/server/wsgi_logger.c(147): [client 188.163.113.8:47306]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:31:40 2022] [error] [pid 85576] src/server/wsgi_logger.c(147): [client 188.163.113.8:47306] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:31:43 2022] [error] [pid 86198] src/server/mod_wsgi.c(3692): [client 188.163.113.8:48174] mod_wsgi (pid=86198): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:31:43 2022] [error] [pid 86198] src/server/wsgi_logger.c(630): [client 188.163.113.8:48174] mod_wsgi (pid=86198): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:31:43 2022] [error] [pid 86198] src/server/wsgi_logger.c(147): [client 188.163.113.8:48174] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:31:43 2022] [error] [pid 86198] src/server/wsgi_logger.c(147): [client 188.163.113.8:48174]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 1, in <module>
www.praiser.pp.ua [Sun Feb 06 20:31:43 2022] [error] [pid 86198] src/server/wsgi_logger.c(147): [client 188.163.113.8:48174]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:31:43 2022] [error] [pid 86198] src/server/wsgi_logger.c(147): [client 188.163.113.8:48174] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:31:43 2022] [error] [pid 86342] src/server/mod_wsgi.c(3692): [client 188.163.113.8:48248] mod_wsgi (pid=86342): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:31:43 2022] [error] [pid 86342] src/server/wsgi_logger.c(630): [client 188.163.113.8:48248] mod_wsgi (pid=86342): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:31:43 2022] [error] [pid 86342] src/server/wsgi_logger.c(147): [client 188.163.113.8:48248] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:31:43 2022] [error] [pid 86342] src/server/wsgi_logger.c(147): [client 188.163.113.8:48248]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 1, in <module>
www.praiser.pp.ua [Sun Feb 06 20:31:43 2022] [error] [pid 86342] src/server/wsgi_logger.c(147): [client 188.163.113.8:48248]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:31:43 2022] [error] [pid 86342] src/server/wsgi_logger.c(147): [client 188.163.113.8:48248] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:32:30 2022] [error] [pid 17971] src/server/mod_wsgi.c(3692): [client 188.163.113.8:57220] mod_wsgi (pid=17971): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:32:30 2022] [error] [pid 17971] src/server/wsgi_logger.c(630): [client 188.163.113.8:57220] mod_wsgi (pid=17971): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:32:30 2022] [error] [pid 17971] src/server/wsgi_logger.c(147): [client 188.163.113.8:57220] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:32:30 2022] [error] [pid 17971] src/server/wsgi_logger.c(147): [client 188.163.113.8:57220]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 1, in <module>
www.praiser.pp.ua [Sun Feb 06 20:32:30 2022] [error] [pid 17971] src/server/wsgi_logger.c(147): [client 188.163.113.8:57220]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:32:30 2022] [error] [pid 17971] src/server/wsgi_logger.c(147): [client 188.163.113.8:57220] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:32:30 2022] [error] [pid 18350] src/server/mod_wsgi.c(3692): [client 188.163.113.8:57276] mod_wsgi (pid=18350): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:32:30 2022] [error] [pid 18350] src/server/wsgi_logger.c(630): [client 188.163.113.8:57276] mod_wsgi (pid=18350): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:32:30 2022] [error] [pid 18350] src/server/wsgi_logger.c(147): [client 188.163.113.8:57276] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:32:30 2022] [error] [pid 18350] src/server/wsgi_logger.c(147): [client 188.163.113.8:57276]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 1, in <module>
www.praiser.pp.ua [Sun Feb 06 20:32:30 2022] [error] [pid 18350] src/server/wsgi_logger.c(147): [client 188.163.113.8:57276]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:32:30 2022] [error] [pid 18350] src/server/wsgi_logger.c(147): [client 188.163.113.8:57276] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:32:37 2022] [error] [pid 22294] src/server/mod_wsgi.c(3692): [client 188.163.113.8:58694] mod_wsgi (pid=22294): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:32:37 2022] [error] [pid 22294] src/server/wsgi_logger.c(630): [client 188.163.113.8:58694] mod_wsgi (pid=22294): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:32:37 2022] [error] [pid 22294] src/server/wsgi_logger.c(147): [client 188.163.113.8:58694] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:32:37 2022] [error] [pid 22294] src/server/wsgi_logger.c(147): [client 188.163.113.8:58694]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 1, in <module>
www.praiser.pp.ua [Sun Feb 06 20:32:37 2022] [error] [pid 22294] src/server/wsgi_logger.c(147): [client 188.163.113.8:58694]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:32:37 2022] [error] [pid 22294] src/server/wsgi_logger.c(147): [client 188.163.113.8:58694] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:32:37 2022] [error] [pid 22985] src/server/mod_wsgi.c(3692): [client 188.163.113.8:58722] mod_wsgi (pid=22985): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:32:37 2022] [error] [pid 22985] src/server/wsgi_logger.c(630): [client 188.163.113.8:58722] mod_wsgi (pid=22985): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:32:37 2022] [error] [pid 22985] src/server/wsgi_logger.c(147): [client 188.163.113.8:58722] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:32:37 2022] [error] [pid 22985] src/server/wsgi_logger.c(147): [client 188.163.113.8:58722]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 1, in <module>
www.praiser.pp.ua [Sun Feb 06 20:32:37 2022] [error] [pid 22985] src/server/wsgi_logger.c(147): [client 188.163.113.8:58722]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:32:37 2022] [error] [pid 22985] src/server/wsgi_logger.c(147): [client 188.163.113.8:58722] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:34:27 2022] [error] [pid 96411] src/server/mod_wsgi.c(3692): [client 188.163.113.8:50782] mod_wsgi (pid=96411): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:34:27 2022] [error] [pid 96411] src/server/wsgi_logger.c(630): [client 188.163.113.8:50782] mod_wsgi (pid=96411): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:34:27 2022] [error] [pid 96411] src/server/wsgi_logger.c(147): [client 188.163.113.8:50782] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:34:27 2022] [error] [pid 96411] src/server/wsgi_logger.c(147): [client 188.163.113.8:50782]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 1, in <module>
www.praiser.pp.ua [Sun Feb 06 20:34:27 2022] [error] [pid 96411] src/server/wsgi_logger.c(147): [client 188.163.113.8:50782]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:34:27 2022] [error] [pid 96411] src/server/wsgi_logger.c(147): [client 188.163.113.8:50782] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:34:27 2022] [error] [pid 96631] src/server/mod_wsgi.c(3692): [client 188.163.113.8:50858] mod_wsgi (pid=96631): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:34:27 2022] [error] [pid 96631] src/server/wsgi_logger.c(630): [client 188.163.113.8:50858] mod_wsgi (pid=96631): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:34:27 2022] [error] [pid 96631] src/server/wsgi_logger.c(147): [client 188.163.113.8:50858] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:34:27 2022] [error] [pid 96631] src/server/wsgi_logger.c(147): [client 188.163.113.8:50858]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 1, in <module>
www.praiser.pp.ua [Sun Feb 06 20:34:27 2022] [error] [pid 96631] src/server/wsgi_logger.c(147): [client 188.163.113.8:50858]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:34:27 2022] [error] [pid 96631] src/server/wsgi_logger.c(147): [client 188.163.113.8:50858] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:37:56 2022] [error] [pid 105748] src/server/mod_wsgi.c(3692): [client 188.163.113.8:36698] mod_wsgi (pid=105748): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:37:56 2022] [error] [pid 105748] src/server/wsgi_logger.c(630): [client 188.163.113.8:36698] mod_wsgi (pid=105748): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:37:56 2022] [error] [pid 105748] src/server/wsgi_logger.c(147): [client 188.163.113.8:36698] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:37:56 2022] [error] [pid 105748] src/server/wsgi_logger.c(147): [client 188.163.113.8:36698]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 15, in <module>
www.praiser.pp.ua [Sun Feb 06 20:37:56 2022] [error] [pid 105748] src/server/wsgi_logger.c(147): [client 188.163.113.8:36698]     application = get_wsgi_application()
www.praiser.pp.ua [Sun Feb 06 20:37:56 2022] [error] [pid 105748] src/server/wsgi_logger.c(147): [client 188.163.113.8:36698] NameError: name 'get_wsgi_application' is not defined
www.praiser.pp.ua [Sun Feb 06 20:37:56 2022] [error] [pid 106091] src/server/mod_wsgi.c(3692): [client 188.163.113.8:36754] mod_wsgi (pid=106091): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:37:56 2022] [error] [pid 106091] src/server/wsgi_logger.c(630): [client 188.163.113.8:36754] mod_wsgi (pid=106091): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:37:56 2022] [error] [pid 106091] src/server/wsgi_logger.c(147): [client 188.163.113.8:36754] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:37:56 2022] [error] [pid 106091] src/server/wsgi_logger.c(147): [client 188.163.113.8:36754]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 15, in <module>
www.praiser.pp.ua [Sun Feb 06 20:37:56 2022] [error] [pid 106091] src/server/wsgi_logger.c(147): [client 188.163.113.8:36754]     application = get_wsgi_application()
www.praiser.pp.ua [Sun Feb 06 20:37:56 2022] [error] [pid 106091] src/server/wsgi_logger.c(147): [client 188.163.113.8:36754] NameError: name 'get_wsgi_application' is not defined
www.praiser.pp.ua [Sun Feb 06 20:37:59 2022] [error] [pid 991] src/server/mod_wsgi.c(3692): [client 188.163.113.8:37418] mod_wsgi (pid=991): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:37:59 2022] [error] [pid 991] src/server/wsgi_logger.c(630): [client 188.163.113.8:37418] mod_wsgi (pid=991): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:37:59 2022] [error] [pid 991] src/server/wsgi_logger.c(147): [client 188.163.113.8:37418] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:37:59 2022] [error] [pid 991] src/server/wsgi_logger.c(147): [client 188.163.113.8:37418]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 15, in <module>
www.praiser.pp.ua [Sun Feb 06 20:37:59 2022] [error] [pid 991] src/server/wsgi_logger.c(147): [client 188.163.113.8:37418]     application = get_wsgi_application()
www.praiser.pp.ua [Sun Feb 06 20:37:59 2022] [error] [pid 991] src/server/wsgi_logger.c(147): [client 188.163.113.8:37418] NameError: name 'get_wsgi_application' is not defined
www.praiser.pp.ua [Sun Feb 06 20:37:59 2022] [error] [pid 1003] src/server/mod_wsgi.c(3692): [client 188.163.113.8:37454] mod_wsgi (pid=1003): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:37:59 2022] [error] [pid 1003] src/server/wsgi_logger.c(630): [client 188.163.113.8:37454] mod_wsgi (pid=1003): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:37:59 2022] [error] [pid 1003] src/server/wsgi_logger.c(147): [client 188.163.113.8:37454] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:37:59 2022] [error] [pid 1003] src/server/wsgi_logger.c(147): [client 188.163.113.8:37454]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 15, in <module>
www.praiser.pp.ua [Sun Feb 06 20:37:59 2022] [error] [pid 1003] src/server/wsgi_logger.c(147): [client 188.163.113.8:37454]     application = get_wsgi_application()
www.praiser.pp.ua [Sun Feb 06 20:37:59 2022] [error] [pid 1003] src/server/wsgi_logger.c(147): [client 188.163.113.8:37454] NameError: name 'get_wsgi_application' is not defined
www.praiser.pp.ua [Sun Feb 06 20:38:00 2022] [error] [pid 1245] src/server/mod_wsgi.c(3692): [client 188.163.113.8:37748] mod_wsgi (pid=1245): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:38:00 2022] [error] [pid 1245] src/server/wsgi_logger.c(630): [client 188.163.113.8:37748] mod_wsgi (pid=1245): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:38:00 2022] [error] [pid 1245] src/server/wsgi_logger.c(147): [client 188.163.113.8:37748] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:38:00 2022] [error] [pid 1245] src/server/wsgi_logger.c(147): [client 188.163.113.8:37748]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 15, in <module>
www.praiser.pp.ua [Sun Feb 06 20:38:00 2022] [error] [pid 1245] src/server/wsgi_logger.c(147): [client 188.163.113.8:37748]     application = get_wsgi_application()
www.praiser.pp.ua [Sun Feb 06 20:38:00 2022] [error] [pid 1245] src/server/wsgi_logger.c(147): [client 188.163.113.8:37748] NameError: name 'get_wsgi_application' is not defined
www.praiser.pp.ua [Sun Feb 06 20:38:01 2022] [error] [pid 1459] src/server/mod_wsgi.c(3692): [client 188.163.113.8:37776] mod_wsgi (pid=1459): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:38:01 2022] [error] [pid 1459] src/server/wsgi_logger.c(630): [client 188.163.113.8:37776] mod_wsgi (pid=1459): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:38:01 2022] [error] [pid 1459] src/server/wsgi_logger.c(147): [client 188.163.113.8:37776] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:38:01 2022] [error] [pid 1459] src/server/wsgi_logger.c(147): [client 188.163.113.8:37776]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 15, in <module>
www.praiser.pp.ua [Sun Feb 06 20:38:01 2022] [error] [pid 1459] src/server/wsgi_logger.c(147): [client 188.163.113.8:37776]     application = get_wsgi_application()
www.praiser.pp.ua [Sun Feb 06 20:38:01 2022] [error] [pid 1459] src/server/wsgi_logger.c(147): [client 188.163.113.8:37776] NameError: name 'get_wsgi_application' is not defined
www.praiser.pp.ua [Sun Feb 06 20:44:18 2022] [error] [pid 11095] src/server/mod_wsgi.c(3692): [client 188.163.113.8:55716] mod_wsgi (pid=11095): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:44:18 2022] [error] [pid 11095] src/server/wsgi_logger.c(630): [client 188.163.113.8:55716] mod_wsgi (pid=11095): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:44:18 2022] [error] [pid 11095] src/server/wsgi_logger.c(147): [client 188.163.113.8:55716] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:44:18 2022] [error] [pid 11095] src/server/wsgi_logger.c(147): [client 188.163.113.8:55716]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:44:18 2022] [error] [pid 11095] src/server/wsgi_logger.c(147): [client 188.163.113.8:55716]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:44:18 2022] [error] [pid 11095] src/server/wsgi_logger.c(147): [client 188.163.113.8:55716] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:44:18 2022] [error] [pid 11150] src/server/mod_wsgi.c(3692): [client 188.163.113.8:55768] mod_wsgi (pid=11150): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:44:18 2022] [error] [pid 11150] src/server/wsgi_logger.c(630): [client 188.163.113.8:55768] mod_wsgi (pid=11150): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:44:18 2022] [error] [pid 11150] src/server/wsgi_logger.c(147): [client 188.163.113.8:55768] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:44:18 2022] [error] [pid 11150] src/server/wsgi_logger.c(147): [client 188.163.113.8:55768]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:44:18 2022] [error] [pid 11150] src/server/wsgi_logger.c(147): [client 188.163.113.8:55768]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:44:18 2022] [error] [pid 11150] src/server/wsgi_logger.c(147): [client 188.163.113.8:55768] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:44:20 2022] [error] [pid 11502] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56008] mod_wsgi (pid=11502): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:44:20 2022] [error] [pid 11502] src/server/wsgi_logger.c(630): [client 188.163.113.8:56008] mod_wsgi (pid=11502): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:44:20 2022] [error] [pid 11502] src/server/wsgi_logger.c(147): [client 188.163.113.8:56008] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:44:20 2022] [error] [pid 11502] src/server/wsgi_logger.c(147): [client 188.163.113.8:56008]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:44:20 2022] [error] [pid 11502] src/server/wsgi_logger.c(147): [client 188.163.113.8:56008]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:44:20 2022] [error] [pid 11502] src/server/wsgi_logger.c(147): [client 188.163.113.8:56008] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:44:20 2022] [error] [pid 11526] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56048] mod_wsgi (pid=11526): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:44:20 2022] [error] [pid 11526] src/server/wsgi_logger.c(630): [client 188.163.113.8:56048] mod_wsgi (pid=11526): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:44:20 2022] [error] [pid 11526] src/server/wsgi_logger.c(147): [client 188.163.113.8:56048] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:44:20 2022] [error] [pid 11526] src/server/wsgi_logger.c(147): [client 188.163.113.8:56048]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:44:20 2022] [error] [pid 11526] src/server/wsgi_logger.c(147): [client 188.163.113.8:56048]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:44:20 2022] [error] [pid 11526] src/server/wsgi_logger.c(147): [client 188.163.113.8:56048] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11787] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56136] mod_wsgi (pid=11787): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11787] src/server/wsgi_logger.c(630): [client 188.163.113.8:56136] mod_wsgi (pid=11787): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11787] src/server/wsgi_logger.c(147): [client 188.163.113.8:56136] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11787] src/server/wsgi_logger.c(147): [client 188.163.113.8:56136]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11787] src/server/wsgi_logger.c(147): [client 188.163.113.8:56136]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11787] src/server/wsgi_logger.c(147): [client 188.163.113.8:56136] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11816] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56174] mod_wsgi (pid=11816): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11816] src/server/wsgi_logger.c(630): [client 188.163.113.8:56174] mod_wsgi (pid=11816): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11816] src/server/wsgi_logger.c(147): [client 188.163.113.8:56174] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11816] src/server/wsgi_logger.c(147): [client 188.163.113.8:56174]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11816] src/server/wsgi_logger.c(147): [client 188.163.113.8:56174]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11816] src/server/wsgi_logger.c(147): [client 188.163.113.8:56174] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11834] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56216] mod_wsgi (pid=11834): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11834] src/server/wsgi_logger.c(630): [client 188.163.113.8:56216] mod_wsgi (pid=11834): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11834] src/server/wsgi_logger.c(147): [client 188.163.113.8:56216] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11834] src/server/wsgi_logger.c(147): [client 188.163.113.8:56216]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11834] src/server/wsgi_logger.c(147): [client 188.163.113.8:56216]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:44:21 2022] [error] [pid 11834] src/server/wsgi_logger.c(147): [client 188.163.113.8:56216] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12486] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56358] mod_wsgi (pid=12486): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12486] src/server/wsgi_logger.c(630): [client 188.163.113.8:56358] mod_wsgi (pid=12486): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12486] src/server/wsgi_logger.c(147): [client 188.163.113.8:56358] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12486] src/server/wsgi_logger.c(147): [client 188.163.113.8:56358]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12486] src/server/wsgi_logger.c(147): [client 188.163.113.8:56358]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12486] src/server/wsgi_logger.c(147): [client 188.163.113.8:56358] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12491] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56372] mod_wsgi (pid=12491): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12491] src/server/wsgi_logger.c(630): [client 188.163.113.8:56372] mod_wsgi (pid=12491): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12491] src/server/wsgi_logger.c(147): [client 188.163.113.8:56372] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12491] src/server/wsgi_logger.c(147): [client 188.163.113.8:56372]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12491] src/server/wsgi_logger.c(147): [client 188.163.113.8:56372]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12491] src/server/wsgi_logger.c(147): [client 188.163.113.8:56372] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12631] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56442] mod_wsgi (pid=12631): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12631] src/server/wsgi_logger.c(630): [client 188.163.113.8:56442] mod_wsgi (pid=12631): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12631] src/server/wsgi_logger.c(147): [client 188.163.113.8:56442] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12631] src/server/wsgi_logger.c(147): [client 188.163.113.8:56442]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12631] src/server/wsgi_logger.c(147): [client 188.163.113.8:56442]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:44:22 2022] [error] [pid 12631] src/server/wsgi_logger.c(147): [client 188.163.113.8:56442] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:48:14 2022] [error] [pid 47900] src/server/mod_wsgi.c(3692): [client 188.163.113.8:40228] mod_wsgi (pid=47900): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:48:14 2022] [error] [pid 47900] src/server/wsgi_logger.c(630): [client 188.163.113.8:40228] mod_wsgi (pid=47900): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:48:14 2022] [error] [pid 47900] src/server/wsgi_logger.c(147): [client 188.163.113.8:40228] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:48:14 2022] [error] [pid 47900] src/server/wsgi_logger.c(147): [client 188.163.113.8:40228]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:48:14 2022] [error] [pid 47900] src/server/wsgi_logger.c(147): [client 188.163.113.8:40228]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:48:14 2022] [error] [pid 47900] src/server/wsgi_logger.c(147): [client 188.163.113.8:40228] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:48:14 2022] [error] [pid 47911] src/server/mod_wsgi.c(3692): [client 188.163.113.8:40292] mod_wsgi (pid=47911): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:48:14 2022] [error] [pid 47911] src/server/wsgi_logger.c(630): [client 188.163.113.8:40292] mod_wsgi (pid=47911): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:48:14 2022] [error] [pid 47911] src/server/wsgi_logger.c(147): [client 188.163.113.8:40292] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:48:14 2022] [error] [pid 47911] src/server/wsgi_logger.c(147): [client 188.163.113.8:40292]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:48:14 2022] [error] [pid 47911] src/server/wsgi_logger.c(147): [client 188.163.113.8:40292]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:48:14 2022] [error] [pid 47911] src/server/wsgi_logger.c(147): [client 188.163.113.8:40292] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48094] src/server/mod_wsgi.c(3692): [client 188.163.113.8:40450] mod_wsgi (pid=48094): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48094] src/server/wsgi_logger.c(630): [client 188.163.113.8:40450] mod_wsgi (pid=48094): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48094] src/server/wsgi_logger.c(147): [client 188.163.113.8:40450] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48094] src/server/wsgi_logger.c(147): [client 188.163.113.8:40450]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48094] src/server/wsgi_logger.c(147): [client 188.163.113.8:40450]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48094] src/server/wsgi_logger.c(147): [client 188.163.113.8:40450] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48106] src/server/mod_wsgi.c(3692): [client 188.163.113.8:40488] mod_wsgi (pid=48106): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48106] src/server/wsgi_logger.c(630): [client 188.163.113.8:40488] mod_wsgi (pid=48106): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48106] src/server/wsgi_logger.c(147): [client 188.163.113.8:40488] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48106] src/server/wsgi_logger.c(147): [client 188.163.113.8:40488]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48106] src/server/wsgi_logger.c(147): [client 188.163.113.8:40488]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48106] src/server/wsgi_logger.c(147): [client 188.163.113.8:40488] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48226] src/server/mod_wsgi.c(3692): [client 188.163.113.8:40554] mod_wsgi (pid=48226): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48226] src/server/wsgi_logger.c(630): [client 188.163.113.8:40554] mod_wsgi (pid=48226): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48226] src/server/wsgi_logger.c(147): [client 188.163.113.8:40554] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48226] src/server/wsgi_logger.c(147): [client 188.163.113.8:40554]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48226] src/server/wsgi_logger.c(147): [client 188.163.113.8:40554]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:48:15 2022] [error] [pid 48226] src/server/wsgi_logger.c(147): [client 188.163.113.8:40554] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48359] src/server/mod_wsgi.c(3692): [client 188.163.113.8:40588] mod_wsgi (pid=48359): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48359] src/server/wsgi_logger.c(630): [client 188.163.113.8:40588] mod_wsgi (pid=48359): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48359] src/server/wsgi_logger.c(147): [client 188.163.113.8:40588] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48359] src/server/wsgi_logger.c(147): [client 188.163.113.8:40588]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48359] src/server/wsgi_logger.c(147): [client 188.163.113.8:40588]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48359] src/server/wsgi_logger.c(147): [client 188.163.113.8:40588] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48373] src/server/mod_wsgi.c(3692): [client 188.163.113.8:40626] mod_wsgi (pid=48373): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48373] src/server/wsgi_logger.c(630): [client 188.163.113.8:40626] mod_wsgi (pid=48373): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48373] src/server/wsgi_logger.c(147): [client 188.163.113.8:40626] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48373] src/server/wsgi_logger.c(147): [client 188.163.113.8:40626]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48373] src/server/wsgi_logger.c(147): [client 188.163.113.8:40626]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48373] src/server/wsgi_logger.c(147): [client 188.163.113.8:40626] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48482] src/server/mod_wsgi.c(3692): [client 188.163.113.8:40676] mod_wsgi (pid=48482): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48482] src/server/wsgi_logger.c(630): [client 188.163.113.8:40676] mod_wsgi (pid=48482): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48482] src/server/wsgi_logger.c(147): [client 188.163.113.8:40676] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48482] src/server/wsgi_logger.c(147): [client 188.163.113.8:40676]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48482] src/server/wsgi_logger.c(147): [client 188.163.113.8:40676]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:48:16 2022] [error] [pid 48482] src/server/wsgi_logger.c(147): [client 188.163.113.8:40676] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 48555] src/server/mod_wsgi.c(3692): [client 188.163.113.8:40752] mod_wsgi (pid=48555): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 48555] src/server/wsgi_logger.c(630): [client 188.163.113.8:40752] mod_wsgi (pid=48555): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 48555] src/server/wsgi_logger.c(147): [client 188.163.113.8:40752] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 48555] src/server/wsgi_logger.c(147): [client 188.163.113.8:40752]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 48555] src/server/wsgi_logger.c(147): [client 188.163.113.8:40752]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 48555] src/server/wsgi_logger.c(147): [client 188.163.113.8:40752] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 48913] src/server/mod_wsgi.c(3692): [client 188.163.113.8:40786] mod_wsgi (pid=48913): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 48913] src/server/wsgi_logger.c(630): [client 188.163.113.8:40786] mod_wsgi (pid=48913): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 48913] src/server/wsgi_logger.c(147): [client 188.163.113.8:40786] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 48913] src/server/wsgi_logger.c(147): [client 188.163.113.8:40786]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 48913] src/server/wsgi_logger.c(147): [client 188.163.113.8:40786]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 48913] src/server/wsgi_logger.c(147): [client 188.163.113.8:40786] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 49092] src/server/mod_wsgi.c(3692): [client 188.163.113.8:40930] mod_wsgi (pid=49092): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 49092] src/server/wsgi_logger.c(630): [client 188.163.113.8:40930] mod_wsgi (pid=49092): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 49092] src/server/wsgi_logger.c(147): [client 188.163.113.8:40930] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 49092] src/server/wsgi_logger.c(147): [client 188.163.113.8:40930]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 49092] src/server/wsgi_logger.c(147): [client 188.163.113.8:40930]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:48:17 2022] [error] [pid 49092] src/server/wsgi_logger.c(147): [client 188.163.113.8:40930] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:48:18 2022] [error] [pid 49106] src/server/mod_wsgi.c(3692): [client 188.163.113.8:40964] mod_wsgi (pid=49106): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:48:18 2022] [error] [pid 49106] src/server/wsgi_logger.c(630): [client 188.163.113.8:40964] mod_wsgi (pid=49106): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:48:18 2022] [error] [pid 49106] src/server/wsgi_logger.c(147): [client 188.163.113.8:40964] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:48:18 2022] [error] [pid 49106] src/server/wsgi_logger.c(147): [client 188.163.113.8:40964]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:48:18 2022] [error] [pid 49106] src/server/wsgi_logger.c(147): [client 188.163.113.8:40964]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:48:18 2022] [error] [pid 49106] src/server/wsgi_logger.c(147): [client 188.163.113.8:40964] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:50:27 2022] [error] [pid 10415] src/server/mod_wsgi.c(3692): [client 188.163.113.8:35430] mod_wsgi (pid=10415): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:50:27 2022] [error] [pid 10415] src/server/wsgi_logger.c(630): [client 188.163.113.8:35430] mod_wsgi (pid=10415): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:50:27 2022] [error] [pid 10415] src/server/wsgi_logger.c(147): [client 188.163.113.8:35430] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:50:27 2022] [error] [pid 10415] src/server/wsgi_logger.c(147): [client 188.163.113.8:35430]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:50:27 2022] [error] [pid 10415] src/server/wsgi_logger.c(147): [client 188.163.113.8:35430]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:50:27 2022] [error] [pid 10415] src/server/wsgi_logger.c(147): [client 188.163.113.8:35430] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:50:27 2022] [error] [pid 10652] src/server/mod_wsgi.c(3692): [client 188.163.113.8:35466] mod_wsgi (pid=10652): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:50:27 2022] [error] [pid 10652] src/server/wsgi_logger.c(630): [client 188.163.113.8:35466] mod_wsgi (pid=10652): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:50:27 2022] [error] [pid 10652] src/server/wsgi_logger.c(147): [client 188.163.113.8:35466] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:50:27 2022] [error] [pid 10652] src/server/wsgi_logger.c(147): [client 188.163.113.8:35466]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:50:27 2022] [error] [pid 10652] src/server/wsgi_logger.c(147): [client 188.163.113.8:35466]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:50:27 2022] [error] [pid 10652] src/server/wsgi_logger.c(147): [client 188.163.113.8:35466] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:50:28 2022] [error] [pid 10966] src/server/mod_wsgi.c(3692): [client 188.163.113.8:35784] mod_wsgi (pid=10966): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:50:28 2022] [error] [pid 10966] src/server/wsgi_logger.c(630): [client 188.163.113.8:35784] mod_wsgi (pid=10966): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:50:28 2022] [error] [pid 10966] src/server/wsgi_logger.c(147): [client 188.163.113.8:35784] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:50:28 2022] [error] [pid 10966] src/server/wsgi_logger.c(147): [client 188.163.113.8:35784]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:50:28 2022] [error] [pid 10966] src/server/wsgi_logger.c(147): [client 188.163.113.8:35784]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:50:28 2022] [error] [pid 10966] src/server/wsgi_logger.c(147): [client 188.163.113.8:35784] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:50:29 2022] [error] [pid 10980] src/server/mod_wsgi.c(3692): [client 188.163.113.8:35824] mod_wsgi (pid=10980): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:50:29 2022] [error] [pid 10980] src/server/wsgi_logger.c(630): [client 188.163.113.8:35824] mod_wsgi (pid=10980): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:50:29 2022] [error] [pid 10980] src/server/wsgi_logger.c(147): [client 188.163.113.8:35824] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:50:29 2022] [error] [pid 10980] src/server/wsgi_logger.c(147): [client 188.163.113.8:35824]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:50:29 2022] [error] [pid 10980] src/server/wsgi_logger.c(147): [client 188.163.113.8:35824]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:50:29 2022] [error] [pid 10980] src/server/wsgi_logger.c(147): [client 188.163.113.8:35824] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:51:53 2022] [error] [pid 49548] src/server/mod_wsgi.c(3692): [client 188.163.113.8:53938] mod_wsgi (pid=49548): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:51:53 2022] [error] [pid 49548] src/server/wsgi_logger.c(630): [client 188.163.113.8:53938] mod_wsgi (pid=49548): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:51:53 2022] [error] [pid 49548] src/server/wsgi_logger.c(147): [client 188.163.113.8:53938] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:51:53 2022] [error] [pid 49548] src/server/wsgi_logger.c(147): [client 188.163.113.8:53938]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:51:53 2022] [error] [pid 49548] src/server/wsgi_logger.c(147): [client 188.163.113.8:53938]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:51:53 2022] [error] [pid 49548] src/server/wsgi_logger.c(147): [client 188.163.113.8:53938] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:51:54 2022] [error] [pid 49709] src/server/mod_wsgi.c(3692): [client 188.163.113.8:53990] mod_wsgi (pid=49709): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:51:54 2022] [error] [pid 49709] src/server/wsgi_logger.c(630): [client 188.163.113.8:53990] mod_wsgi (pid=49709): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Sun Feb 06 20:51:54 2022] [error] [pid 49709] src/server/wsgi_logger.c(147): [client 188.163.113.8:53990] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:51:54 2022] [error] [pid 49709] src/server/wsgi_logger.c(147): [client 188.163.113.8:53990]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:51:54 2022] [error] [pid 49709] src/server/wsgi_logger.c(147): [client 188.163.113.8:53990]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:51:54 2022] [error] [pid 49709] src/server/wsgi_logger.c(147): [client 188.163.113.8:53990] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:56:16 2022] [error] [pid 90593] src/server/mod_wsgi.c(3692): [client 188.163.113.8:46854] mod_wsgi (pid=90593): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:56:16 2022] [error] [pid 90593] src/server/wsgi_logger.c(630): [client 188.163.113.8:46854] mod_wsgi (pid=90593): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Sun Feb 06 20:56:16 2022] [error] [pid 90593] src/server/wsgi_logger.c(147): [client 188.163.113.8:46854] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:56:16 2022] [error] [pid 90593] src/server/wsgi_logger.c(147): [client 188.163.113.8:46854]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:56:16 2022] [error] [pid 90593] src/server/wsgi_logger.c(147): [client 188.163.113.8:46854]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:56:16 2022] [error] [pid 90593] src/server/wsgi_logger.c(147): [client 188.163.113.8:46854] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:56:16 2022] [error] [pid 90610] src/server/mod_wsgi.c(3692): [client 188.163.113.8:46892] mod_wsgi (pid=90610): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:56:16 2022] [error] [pid 90610] src/server/wsgi_logger.c(630): [client 188.163.113.8:46892] mod_wsgi (pid=90610): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Sun Feb 06 20:56:16 2022] [error] [pid 90610] src/server/wsgi_logger.c(147): [client 188.163.113.8:46892] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:56:16 2022] [error] [pid 90610] src/server/wsgi_logger.c(147): [client 188.163.113.8:46892]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:56:16 2022] [error] [pid 90610] src/server/wsgi_logger.c(147): [client 188.163.113.8:46892]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:56:16 2022] [error] [pid 90610] src/server/wsgi_logger.c(147): [client 188.163.113.8:46892] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:56:18 2022] [error] [pid 91179] src/server/mod_wsgi.c(3692): [client 188.163.113.8:47222] mod_wsgi (pid=91179): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:56:18 2022] [error] [pid 91179] src/server/wsgi_logger.c(630): [client 188.163.113.8:47222] mod_wsgi (pid=91179): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Sun Feb 06 20:56:18 2022] [error] [pid 91179] src/server/wsgi_logger.c(147): [client 188.163.113.8:47222] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:56:18 2022] [error] [pid 91179] src/server/wsgi_logger.c(147): [client 188.163.113.8:47222]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:56:18 2022] [error] [pid 91179] src/server/wsgi_logger.c(147): [client 188.163.113.8:47222]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:56:18 2022] [error] [pid 91179] src/server/wsgi_logger.c(147): [client 188.163.113.8:47222] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:56:18 2022] [error] [pid 91193] src/server/mod_wsgi.c(3692): [client 188.163.113.8:47258] mod_wsgi (pid=91193): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:56:18 2022] [error] [pid 91193] src/server/wsgi_logger.c(630): [client 188.163.113.8:47258] mod_wsgi (pid=91193): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Sun Feb 06 20:56:18 2022] [error] [pid 91193] src/server/wsgi_logger.c(147): [client 188.163.113.8:47258] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:56:18 2022] [error] [pid 91193] src/server/wsgi_logger.c(147): [client 188.163.113.8:47258]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:56:18 2022] [error] [pid 91193] src/server/wsgi_logger.c(147): [client 188.163.113.8:47258]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:56:18 2022] [error] [pid 91193] src/server/wsgi_logger.c(147): [client 188.163.113.8:47258] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:56:22 2022] [error] [pid 92538] src/server/mod_wsgi.c(3692): [client 188.163.113.8:47946] mod_wsgi (pid=92538): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:56:22 2022] [error] [pid 92538] src/server/wsgi_logger.c(630): [client 188.163.113.8:47946] mod_wsgi (pid=92538): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Sun Feb 06 20:56:22 2022] [error] [pid 92538] src/server/wsgi_logger.c(147): [client 188.163.113.8:47946] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:56:22 2022] [error] [pid 92538] src/server/wsgi_logger.c(147): [client 188.163.113.8:47946]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:56:22 2022] [error] [pid 92538] src/server/wsgi_logger.c(147): [client 188.163.113.8:47946]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:56:22 2022] [error] [pid 92538] src/server/wsgi_logger.c(147): [client 188.163.113.8:47946] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:56:22 2022] [error] [pid 92641] src/server/mod_wsgi.c(3692): [client 188.163.113.8:47984] mod_wsgi (pid=92641): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:56:22 2022] [error] [pid 92641] src/server/wsgi_logger.c(630): [client 188.163.113.8:47984] mod_wsgi (pid=92641): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Sun Feb 06 20:56:22 2022] [error] [pid 92641] src/server/wsgi_logger.c(147): [client 188.163.113.8:47984] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:56:22 2022] [error] [pid 92641] src/server/wsgi_logger.c(147): [client 188.163.113.8:47984]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:56:22 2022] [error] [pid 92641] src/server/wsgi_logger.c(147): [client 188.163.113.8:47984]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:56:22 2022] [error] [pid 92641] src/server/wsgi_logger.c(147): [client 188.163.113.8:47984] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:56:24 2022] [error] [pid 93561] src/server/mod_wsgi.c(3692): [client 188.163.113.8:48394] mod_wsgi (pid=93561): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:56:24 2022] [error] [pid 93561] src/server/wsgi_logger.c(630): [client 188.163.113.8:48394] mod_wsgi (pid=93561): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Sun Feb 06 20:56:24 2022] [error] [pid 93561] src/server/wsgi_logger.c(147): [client 188.163.113.8:48394] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:56:24 2022] [error] [pid 93561] src/server/wsgi_logger.c(147): [client 188.163.113.8:48394]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:56:24 2022] [error] [pid 93561] src/server/wsgi_logger.c(147): [client 188.163.113.8:48394]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:56:24 2022] [error] [pid 93561] src/server/wsgi_logger.c(147): [client 188.163.113.8:48394] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:56:25 2022] [error] [pid 93606] src/server/mod_wsgi.c(3692): [client 188.163.113.8:48494] mod_wsgi (pid=93606): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:56:25 2022] [error] [pid 93606] src/server/wsgi_logger.c(630): [client 188.163.113.8:48494] mod_wsgi (pid=93606): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Sun Feb 06 20:56:25 2022] [error] [pid 93606] src/server/wsgi_logger.c(147): [client 188.163.113.8:48494] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:56:25 2022] [error] [pid 93606] src/server/wsgi_logger.c(147): [client 188.163.113.8:48494]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:56:25 2022] [error] [pid 93606] src/server/wsgi_logger.c(147): [client 188.163.113.8:48494]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:56:25 2022] [error] [pid 93606] src/server/wsgi_logger.c(147): [client 188.163.113.8:48494] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:56:26 2022] [error] [pid 93812] src/server/mod_wsgi.c(3692): [client 188.163.113.8:48702] mod_wsgi (pid=93812): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:56:26 2022] [error] [pid 93812] src/server/wsgi_logger.c(630): [client 188.163.113.8:48702] mod_wsgi (pid=93812): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Sun Feb 06 20:56:26 2022] [error] [pid 93812] src/server/wsgi_logger.c(147): [client 188.163.113.8:48702] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:56:26 2022] [error] [pid 93812] src/server/wsgi_logger.c(147): [client 188.163.113.8:48702]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:56:26 2022] [error] [pid 93812] src/server/wsgi_logger.c(147): [client 188.163.113.8:48702]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:56:26 2022] [error] [pid 93812] src/server/wsgi_logger.c(147): [client 188.163.113.8:48702] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Sun Feb 06 20:56:26 2022] [error] [pid 93945] src/server/mod_wsgi.c(3692): [client 188.163.113.8:48742] mod_wsgi (pid=93945): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Sun Feb 06 20:56:26 2022] [error] [pid 93945] src/server/wsgi_logger.c(630): [client 188.163.113.8:48742] mod_wsgi (pid=93945): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Sun Feb 06 20:56:26 2022] [error] [pid 93945] src/server/wsgi_logger.c(147): [client 188.163.113.8:48742] Traceback (most recent call last):
www.praiser.pp.ua [Sun Feb 06 20:56:26 2022] [error] [pid 93945] src/server/wsgi_logger.c(147): [client 188.163.113.8:48742]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 2, in <module>
www.praiser.pp.ua [Sun Feb 06 20:56:26 2022] [error] [pid 93945] src/server/wsgi_logger.c(147): [client 188.163.113.8:48742]     from django.core.handlers import wsgi
www.praiser.pp.ua [Sun Feb 06 20:56:26 2022] [error] [pid 93945] src/server/wsgi_logger.c(147): [client 188.163.113.8:48742] ModuleNotFoundError: No module named 'django'
